# .github/workflows/build.yml

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 캐시 설정
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew build -x test

      - name: SCP를 사용하여 JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/reeltalkbe-0.0.1-SNAPSHOT.jar"
          target: "~/app"
          strip_components: 2

      - name: 원격 서버에서 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -x

            # 설정 파일 및 변수 정의
            APP_DIR="$HOME/app"
            JAR_FILE="reeltalkbe-0.0.1-SNAPSHOT.jar"
            JAR_PATH="$APP_DIR/$JAR_FILE"
            PRIVATE_YML_PATH="$APP_DIR/application-private.yml"
            LOG_FILE="$APP_DIR/nohup.out"

            # application-private.yml 파일 생성
            echo "application-private.yml 파일을 생성합니다."
            echo "${{ secrets.APP_PRIVATE_YML }}" > $PRIVATE_YML_PATH

            # 기존 프로세스 종료
            set +e
            PID=$(pgrep -f "$JAR_FILE")
            if [ -n "$PID" ]; then
              echo "기존 프로세스(PID: $PID)를 종료합니다."
              kill -15 $PID
              sleep 5
            fi
            set -e

            # 애플리케이션 시작
            echo "새 애플리케이션을 시작합니다 (private 프로필 활성화)."
            nohup java -jar "$JAR_PATH" --spring.profiles.active=private > "$LOG_FILE" 2>&1 &

            echo "배포 스크립트가 완료되었습니다. 10초 후 로그를 확인합니다."
            sleep 10
            cat $LOG_FILE
