# .github/workflows/main.yml

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드
        run: ./gradlew build

      - name: JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar"
          target: "~/" # app 디렉토리 없이 홈으로 바로 지정

      - name: 원격 서버에서 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 기존에 실행 중인 Java 프로세스 종료
            PID=$(pgrep -f 'reeltalkbe-.*.jar')
            if [ -n "$PID" ]; then
              echo "기존 프로세스(PID: $PID)를 종료합니다."
              kill -15 $PID
              sleep 5
            fi
            
            # 새 JAR 파일 실행 (홈 디렉토리 경로로 수정)
            echo "새 애플리케이션을 시작합니다."
            nohup java -jar ~/*.jar > ~/nohup.out 2>&1 &