# .github/workflows/build.yml

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 캐시 설정
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew build -x test

      - name: application-private.yml 파일 생성
        run: echo "${{ secrets.APP_PRIVATE_YML }}" > src/main/resources/application-private.yml

      - name: SCP를 사용하여 빌드 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar,src/main/resources/application-private.yml"
          target: "~/app"
          strip_components: 2

      - name: 기존 프로세스 종료 (오류 무시)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            pkill -f 'reeltalkbe-.*.jar' || true
          
      - name: 새 애플리케이션 배포 및 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            APP_DIR="$HOME/app"
            JAR_FILE=$(ls $APP_DIR/reeltalkbe-*.jar | head -n 1)
            LOG_FILE="$APP_DIR/nohup.out"

            echo "새 애플리케이션을 시작합니다."
            nohup java -jar "$JAR_FILE" --spring.profiles.active=private > "$LOG_FILE" 2>&1 &
            
            echo "배포 스크립트가 완료되었습니다. 10초 후 로그를 확인합니다."
            sleep 10
            cat $LOG_FILE
