on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 빌드
        # 빌드 전 권한 부여
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/reeltalkbe-*.jar" # 1. JAR 파일 이름 변경
          target: "~/"

      - name: 원격 서버에서 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 2. application.yml 파일 생성
            echo "${{ secrets.APP_PRIVATE_YML }}" > ~/application.yml

            # 3. 기존에 실행 중인 reeltalkbe 프로세스 종료
            pkill -f reeltalkbe-*.jar || true

            # 4. 새로운 JAR 파일 실행
            nohup java -jar ~/reeltalkbe-*.jar --spring.config.location=~/application.yml > ~/nohup.out 2>&1 &