name: Deploy on PR Merge to Main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew build

      - name: Find latest JAR file
        id: find_jar
        run: |
          LATEST_JAR=$(ls -t build/libs/*.jar | head -1)
          echo "LATEST_JAR=$LATEST_JAR" >> $GITHUB_OUTPUT
          echo "찾은 JAR 파일: $LATEST_JAR"

      - name: JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ${{ steps.find_jar.outputs.LATEST_JAR }}
          target: "~/"

      - name: 원격 서버에서 JAR 실행 (배포)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          sync: false
          request_pty: false
          script: |
            JAR_FILENAME=$(basename "${{ steps.find_jar.outputs.LATEST_JAR }}")
            DEPLOY_PATH="~/$JAR_FILENAME"

            echo "배포될 JAR 파일 이름: $JAR_FILENAME"
            echo "서버 배포 경로: $DEPLOY_PATH"

            EXISTING_PID=$(ps -ef | grep "$JAR_FILENAME" | grep -v grep | awk '{print $2}')
            if [ -n "$EXISTING_PID" ]; then
              echo "기존 프로세스 (PID: $EXISTING_PID) 종료 중..."
              kill -9 "$EXISTING_PID"
              sleep 5
            else
              echo "실행 중인 기존 프로세스가 없습니다."
            fi

            echo "새로운 JAR 파일 ($JAR_FILENAME) 실행 중..."
            nohup java -jar "$DEPLOY_PATH" > /dev/null 2>&1 < /dev/null &
            disown

            sleep 10
            if ps -ef | grep "$JAR_FILENAME" | grep -v grep > /dev/null; then
              echo "애플리케이션이 서버에서 성공적으로 시작되었습니다."
            else
              echo "애플리케이션 시작에 실패했습니다."
              exit 1
            fi

            exit 0